version: "3.8"

services:

  app:
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: rest_api:MySQL
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db 

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'core'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    container_name: dataBase_container