# Generated by Django 4.1.2 on 2022-12-30 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_app_id_alter_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='app',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='app',
            name='time_create',
        ),
        migrations.RemoveField(
            model_name='app',
            name='time_update',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
